version: '3.7'
# Define services
services:
  mybatis-mysql-db:
    restart: always
    image: mysql:latest
    environment:
      MYSQL_DATABASE: demo
      MYSQL_USER: livhu
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3307:3307
    healthcheck:
      test: "/usr/bin/mysql --user=livhu --password=password \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 3

#    volumes:
#      - db-data:/var/lib/mysql
#    networks:
#      - backend

  #backend service
  balance-dispense-docker:
#    build:
#      context: balance-dispense
#      dockerfile: Dockerfile
    image: discoverybank/balance-dispense
    restart: always
    depends_on:
      - mybatis-mysql-db
    ports:
      - 8089:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mybatis-mysql-db:3307/demo?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: livhu
      SPRING_DATASOURCE_PASSWORD: password

#    networks:
#      - backend

# Volumes
#volumes:
#  db-data:



